config/routes.rb
# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas>

Qpt2a::Application.routes.draw do
  
  root :to => "Home#index"
  
  get "home/index"
  
  resources :home
    match 'about' => "Home#about", :as => "about"
    match 'impressum' => "Home#impressum", :as => "impressum"
    
    
  get "user/register"

  resources :user
    match 'User/logout' => "User#logout", :as => "logout"
    match 'User/register' => "User#registration", :as => "register"
    match 'User/login' => "User#login", :as => "login"
    match 'User/create' => "User#create", :as => "create"
    match 'User/changeMind/:answer/:post_estimation/:post_id' => "User#changeMind", :as => "user_mind", :via => :post
    match 'User/profile' => "User#edit", :as => "profile"
    match 'User/newPassword' => "User#newPassword"
    match "auth/:facebook/callback" => "User#facebookLogin"
  
  resources :daily_news
    match 'chooseTheme' => "DailyNews#chooseTheme", :as => "choose_theme"
    match 'daily_news/:id' => "DailyNews#voteForTheme", :via => :post
 
 
  get "top_stories/discussion"
  get "top_stories/selectPrevDays"

  resources :top_stories
    match 'themeOfDay' => "TopStories#discussion", :as => "top_stories"  
    match 'prevDays/:id' => "TopStories#selectPrevDays", :as => "prev_days"     
    match 'archive' => "TopStories#archive", :as => "archive" 
  
  get "posts/index"
  get "posts/new"
  get "posts/edit"

  resources :posts
    match "posts/:top_story_id/new" => "Posts#new", :as => "new_post"
   
end

app/models/top_story.rb
# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas>

class TopStory < ActiveRecord::Base

  has_many :posts, :dependent => :destroy
   
   
  def isUpToDate?
    created_at.strftime('%d').eql? Time.now.strftime('%d')
  end
  
  def hasDeadlineEnded?
    Time.now.to_s.slice(11..12).to_i > 11 
  end
  
end

app/controllers/top_stories_controller.rb
# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas>

class TopStoriesController < ApplicationController

  def discussion
    
    handler = NewsHandler.new

    # after twelve o clock a new theme is turned into a top story 
    # and new themes are loaded in

    if !handler.isTopStoryUpToDate? && handler.hasTopStoryDeadlineEnded?
      handler.insertThemeIntoTopStoryDatabase
      handler.checkThemeList
    end
    
    @latest_top_story = TopStory.last

  end
  

  def selectPrevDays  
    @top_stories = TopStory.where( :id => params[:id] ).first
  end 
  

  def archive
    @top_stories = TopStory.all
  end

end

app/helpers/top_stories_helper.rb
# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas>

module TopStoriesHelper
  def hasUserAlreadyVoted(usernames, logged_in_user_id)
    
    username_array = usernames.split(" ")
    current_logged_in_user = User.find( logged_in_user_id )
    
    username_array.each do |username|
      if current_logged_in_user.username == username
        return true
      end
    end

    return false

  end
  

  def doesPostBelongToUser(logged_in_user_id, post_of_user)
    if User.find( logged_in_user_id ).username != post_of_user
      return false
    else
      return true
    end
  end
  
end

app/views/top_stories/archive.html.erb
<%# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas> %>

<h2>Tagesthemenarchiv: </h2>

<% @top_stories.each do |story| %>
<div>
<h4><%= story.created_at.strftime('%a, %d.%m.') %></h4>
<%= link_to story.title, prev_days_path(story.id) %>
</div>
<% end %>

app/views/top_stories/discussion.html.erb
<%# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas> %>

<h2>Tagesthema</h2>

<div>
				
<h3><%= raw @latest_top_story.title %></h3>
<div><%= raw @latest_top_story.description %></div>

</div>

<%= link_to 'Kommentar erstellen', new_post_path(@latest_top_story.id) %>

<% @latest_top_story.posts.each do |post| %>

  <div class="post">
  <h4><%= post.title %></h4>
  <%= post.content %><br />
  
  Erstellt am: <span><%= post.created_at.strftime('%d.%m.%Y %H:%M:%S') %></span> Von: <span class="username"><%= post.user.username %></span> Postscore: <%= post.score %><br />
  
  <% if session[:id] && !doesPostBelongToUser(session[:id], post.user.username) && !hasUserAlreadyVoted(post.voted_usernames, session[:id]) %>
    <%= link_to 'Finde ich gut', user_mind_path(1, post.estimation, post.id), :method => :post %>  &lt; &gt;
    <%= link_to 'Finde ich schlecht', user_mind_path(0, post.estimation, post.id), :method => :post %> 
  <% end %>
 
  </div>
  
<% end %>	

app/views/top_stories/selectPrevDays.html.erb
<%# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas> %>

<h2>Tagesthema vom <%= @top_stories.created_at.strftime('%a, %d.%m.') %></h2>
	<h3><%= raw @top_stories.title %></h3>
  <div><%= raw @top_stories.description %></div>

<% @top_stories.posts.each do |post| %>
  
  <div class="post">
  <h4><%= post.title %></h4>
  <%= post.content %><br />
  
  Von: <span class="username"><%= post.user.username %></span> Postscore: <%= post.score %>
  </div>
  
<% end %>