config/routes.rb
# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas>

Qpt2a::Application.routes.draw do
  
  root :to => "Home#index"
  
  get "home/index"
  
  resources :home
    match 'about' => "Home#about", :as => "about"
    match 'impressum' => "Home#impressum", :as => "impressum"
    
    
  get "user/register"

  resources :user
    match 'User/logout' => "User#logout", :as => "logout"
    match 'User/register' => "User#registration", :as => "register"
    match 'User/login' => "User#login", :as => "login"
    match 'User/create' => "User#create", :as => "create"
    match 'User/changeMind/:answer/:post_estimation/:post_id' => "User#changeMind", :as => "user_mind", :via => :post
    match 'User/profile' => "User#edit", :as => "profile"
    match 'User/newPassword' => "User#newPassword"
    match "auth/:facebook/callback" => "User#facebookLogin"
  
  resources :daily_news
    match 'chooseTheme' => "DailyNews#chooseTheme", :as => "choose_theme"
    match 'daily_news/:id' => "DailyNews#voteForTheme", :via => :post
 
 
  get "top_stories/discussion"
  get "top_stories/selectPrevDays"

  resources :top_stories
    match 'themeOfDay' => "TopStories#discussion", :as => "top_stories"  
    match 'prevDays/:id' => "TopStories#selectPrevDays", :as => "prev_days"     
    match 'archive' => "TopStories#archive", :as => "archive" 
  
  get "posts/index"
  get "posts/new"
  get "posts/edit"

  resources :posts
    match "posts/:top_story_id/new" => "Posts#new", :as => "new_post"
   
end

app/views/layouts/application.html.erb
<%# Copyright (C) <2012> <Bruenner Franz Josef, Fritsch Andreas> %>

<!DOCTYPE html>

<html>

<head>

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<title>NewsMinds</title>

<%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>


<script type="text/javascript"></script>
<style type="text/css"></style>

</head>

<body>

<div id="wrapper">

<div id="header">

<% if session[:id].nil? %>

<form action="/auth/facebook">
<table>
<tr><td><input type="submit" value="Facebook-Login" /></td></tr>
</table>
</form>

<form action="<%= login_path %>" method="POST">
<table>
<tr><td><%= link_to 'Registrieren', register_path %></td></tr>
<tr><td><input type="submit" value=" Login " /></td></tr>
<tr><td>Passwort</td><td><input type="password" name="password" /></td></tr>
<tr><td>Username</td><td><input type="username" name="username" /></td></tr>
</table>
</form>
<% else %>

<form action="<%= logout_path %>">
<table>
<tr><td><input type="submit" value=" Logout " /></td></tr>
</table>
</form>

<% end %>

</div>

<div id="logo">
NewsMinds
</div>

<div id="menu">
<ul>
<li><%= link_to 'Home', root_path %></li>

<li><%= link_to 'Tagesthema', top_stories_path %></li>
<li><%= link_to 'Themenwahl', choose_theme_path %></li>

<li><%= link_to 'Archiv', archive_path %></li>

<% if session[:id] %>
  <li><%= link_to 'Kommentare', posts_path %></li>
  <li><%= link_to 'Profil', profile_path %></li>
<% else %>
  <li><%= link_to 'About', about_path %></li>
  <li><%= link_to 'Impressum', impressum_path %></li>
<% end %>
</ul>
</div>

<div id="main">

<div id="content">

<% if flash[:notice] != nil %>
	<div id="notice"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</div>
</div>

<div id="rightbar">

<% if session[:id]  %>
  
  <% user = User.find( session[:id] ) %>

    Eingeloggt als<br />
    <span class="username"><%= user.username %></span><br />
    <br />
	<img src="http://chart.apis.google.com/chart?chf=bg,s,FFFFFF&chxl=0:|Schlecht        ||          Gut&chxt=y&chs=175x110&cht=gm&chd=t:<%= user.mind + 50 %>&chl=<%= user.mind %>" width="175" height="110" alt="" />    
    <span class="votepower">Stimmengewicht: <%= user.votePower %><br />
    Gute Bewertungen: <%= user.numberOfPosVotedPosts %><br />
    Negative Bewertungen: <%= user.numberOfNegVotedPosts %><br />
    Positive Kommentare: <%= user.numberOfPosCreatedPosts %><br />
    Negative Kommentare: <%= user.numberOfNegCreatedPosts %>

<% else %>
  <span class="username">Hier werden deine Statistiken angezeigt, wenn du eingeloggt bist.</span>
<% end %>

</div>

<div id="footer">
<div id="oldthemes">
Letzte Tage: 
<% all_stories = TopStory.all %> 	
    <% for i in 0...all_stories.count do %>
      <%= link_to all_stories[i].created_at.strftime('%a, %d.%m.'), prev_days_path(all_stories[i].id) %>
<% end %>
</div>
<div id="copy">
(c) Brünner + Fritsch 11.2011 <%= link_to 'About', about_path %> <%= link_to 'Impressum', impressum_path %>
</div>
</div>

</div>

</body>

</html>